"""
Certificate template parameter mappings.

Maps each .docx certificate template to its analysis parameters.
Each entry: row (0-based, excl. header), param_name (from docx),
kod (analysis code or None if skipped/qualitative).

Analysis codes: sm, nacl, ph_10proc, nd20, sa, aa, so3, h2o2,
barwa_fau, barwa_hz, gestosc, lk, lz, li, lh, la, wkt, mea,
estry, monoestry, monoglicerydy, wolna_amina, alkalicznosc,
tlenek_aminowy, dietanolamina, wolny_glikol, siarczynow.

Auto-generated from docs/swiadectwa/ templates.
"""

CERT_MAPPINGS = {
    "100099_R175690_0.2026 - Wzór.docx": [
        {"row": 0, "param_name": "Wygląd/Appearance", "kod": None},
        {"row": 1, "param_name": "Barwa / Colour", "kod": None},
        {"row": 2, "param_name": "pH (5%, aq, 25°C)", "kod": "ph_10proc"},
        {"row": 3, "param_name": "Sucha masa (DM) [%]\n/ Dry mass  (DM) [%]", "kod": "sm"},
        {"row": 4, "param_name": "NaCl [%]", "kod": "nacl"},
        {"row": 5, "param_name": "Substancja aktywna (AM) [%]\n/Active matter (AM) [%]", "kod": "sa"},
        {"row": 6, "param_name": "Alkaliczność całkowita [meq/g]\n/Total alkalinity [meq/g]", "kod": "alkalicznosc"},
        {"row": 7, "param_name": "Kwas monochlorooctowy (MCA)\n/ Monochloroacetic acid (MCA)", "kod": None},
        {"row": 8, "param_name": "Kwas dichlorooctowy (DCA)\n/ Dichloroacetic acid (DCA)", "kod": None},
        {"row": 9, "param_name": "Liczba kwasowa [mg KOH/g]\n/Acid value [mg KOH/g]", "kod": "lk"},
        {"row": 10, "param_name": "Liczba aminowa [mg KOH/g]\n/Amine value [mg KOH/g]", "kod": "la"},
    ],
    "AVON Świadectwo - Certificate -Glikoster P WZÓR.docx": [
        {"row": 0, "param_name": "Barwa w skali jodowej\n/Colour (Iodine scale)", "kod": "barwa_hz"},
        {"row": 1, "param_name": "Zapach\n/Odour", "kod": None},
        {"row": 2, "param_name": "Wygląd\n/Appearance", "kod": None},
        {"row": 3, "param_name": "Liczba kwasowa [mg KOH/g]\n/Acid value [mg KOH/g]", "kod": "lk"},
        {"row": 4, "param_name": "Wolny glikol [%]\n/Free glycol [%]", "kod": "wolny_glikol"},
        {"row": 5, "param_name": "Liczba hydroksylowa\n[mg KOH/g]\n/Hydroxyl value [mg KOH/g]", "kod": "lh"},
        {"row": 6, "param_name": "Monoestry [%]\n/Monoesters [%]", "kod": "monoestry"},
        {"row": 7, "param_name": "%C14:0\n%C16:0\n%C18:0&C18:1", "kod": None},
    ],
    "AVON Świadectwo_Certificate-Alkinol B  MB WZÓR.docx": [
        {"row": 0, "param_name": "Barwa w skali jodowej\n/Colour (Iodine scale)", "kod": "barwa_hz"},
        {"row": 1, "param_name": "Zapach/Odour", "kod": None},
        {"row": 2, "param_name": "Wygląd/ Appearance", "kod": None},
        {"row": 3, "param_name": "Liczba kwasowa [mgKOH/g]\n/Acid value [mg KOH/g]", "kod": "lk"},
        {"row": 4, "param_name": "Liczba zmydlania [mg KOH/g]\n/Saponification value\n[mg KOH/g]", "kod": "lz"},
        {"row": 5, "param_name": "Temperatura krzepnięcia [C]\n/Melting point [C]", "kod": None},
        {"row": 6, "param_name": "Liczba hydroksylowa \n[mg KOH/g]\n/Hydroxyl value [mg KOH/g]", "kod": "lh"},
        {"row": 7, "param_name": "Liczba jodowa [g I2/100 g]\n/Iodine value [g I2/100 g]", "kod": "li"},
    ],
    "AVON Świadectwo_Certificate-Chegina KK MB -WZÓR.docx": [
        {"row": 0, "param_name": "Zapach\n/Odour", "kod": None},
        {"row": 1, "param_name": "Wygląd\n/Appearance", "kod": None},
        {"row": 2, "param_name": "pH (10%, 25 C)", "kod": "ph_10proc"},
        {"row": 3, "param_name": "NaCl [%]", "kod": "nacl"},
        {"row": 4, "param_name": "Substancja aktywna [%]\n/Active matter [%]", "kod": "sa"},
        {"row": 5, "param_name": "Zawartość wolnego aminoamidu [%]\n/Free aminoamide [%]", "kod": "wolna_amina"},
        {"row": 6, "param_name": "Barwa w skali jodowej\n/Colour (Iodine scale)", "kod": "barwa_hz"},
        {"row": 7, "param_name": "MCA [ppm]", "kod": None},
        {"row": 8, "param_name": "DCA [ppm]", "kod": None},
        {"row": 9, "param_name": "DMAPA [ppm]", "kod": None},
    ],
    "Certificate Świadectwo-Perlico 45 WZÓR REUSE.docx": [
        {"row": 0, "param_name": "Sucha masa [%]\n/Dry matter [%]", "kod": "sm"},
        {"row": 1, "param_name": "pH (10%, aq, 20°C)", "kod": "ph_10proc"},
    ],
    "Certificate Świadectwo-Perlico 45 WZÓR nr. zamówienia.docx": [
        {"row": 0, "param_name": "Sucha masa [%]\n/Dry matter [%]", "kod": "sm"},
        {"row": 1, "param_name": "pH (10%, aq, 20°C)", "kod": "ph_10proc"},
    ],
    "Certificate Świadectwo-Perlico 45 WZÓR.docx": [
        {"row": 0, "param_name": "Sucha masa [%]\n/Dry matter [%]", "kod": "sm"},
        {"row": 1, "param_name": "pH (10%, aq, 20°C)", "kod": "ph_10proc"},
    ],
    "Chegina K7 188.docx": [
        {"row": 0, "param_name": "Sucha masa [%]\n/Dry matter [%]", "kod": "sm"},
        {"row": 1, "param_name": "NaCl [%]", "kod": "nacl"},
        {"row": 2, "param_name": "Wsp. załamania światła (nD20)\n/Refraction (nD20)", "kod": "nd20"},
        {"row": 3, "param_name": "Barwa w skali jodowej\n/Colour (Iodine scale)", "kod": "barwa_hz"},
        {"row": 4, "param_name": "pH (10%, aq)", "kod": "ph_10proc"},
        {"row": 5, "param_name": "Substancja aktywna [%]\n/Active matter [%]", "kod": "sa"},
    ],
    "LEHVOSS Świadectwo_Certificate- Chegina KK WZÓR.docx": [
        {"row": 0, "param_name": "Zapach/Odour", "kod": None},
        {"row": 1, "param_name": "Wygląd/Appearance", "kod": None},
        {"row": 2, "param_name": "pH (10%, 25 C)", "kod": "ph_10proc"},
        {"row": 3, "param_name": "NaCl [%]", "kod": "nacl"},
        {"row": 4, "param_name": "Substancja aktywna [%]\n/Active matter [%]", "kod": "sa"},
        {"row": 5, "param_name": "Zawartość wolnego aminoamidu [%]\n/Free aminoamide [%]", "kod": "wolna_amina"},
        {"row": 6, "param_name": "Barwa w skali jodowej\n/Colour (Iodine scale)", "kod": "barwa_hz"},
        {"row": 7, "param_name": "MCA [ppm]", "kod": None},
        {"row": 8, "param_name": "DCA [ppm]", "kod": None},
        {"row": 9, "param_name": "DMAPA [ppm]", "kod": None},
    ],
    "PRIME Świadectwo_Certificate-Chegina KK -WZÓR.docx": [
        {"row": 0, "param_name": "Zapach\n/Odour", "kod": None},
        {"row": 1, "param_name": "Wygląd\n/Appearance", "kod": None},
        {"row": 2, "param_name": "pH (10%, 25 C)", "kod": "ph_10proc"},
        {"row": 3, "param_name": "NaCl [%]", "kod": "nacl"},
        {"row": 4, "param_name": "Substancja aktywna [%]\n/Active matter [%]", "kod": "sa"},
        {"row": 5, "param_name": "Zawartość wolnego aminoamidu [%]\n/Free aminoamide [%]", "kod": "wolna_amina"},
        {"row": 6, "param_name": "Barwa w skali jodowej\n/Colour (Iodine scale)", "kod": "barwa_hz"},
        {"row": 7, "param_name": "MCA [ppm]", "kod": None},
        {"row": 8, "param_name": "DCA [ppm]", "kod": None},
        {"row": 9, "param_name": "DMAPA [ppm]", "kod": None},
    ],
    "PRIME Świadectwo_Certificate-Chegina KK MB WZÓR.docx": [
        {"row": 0, "param_name": "Zapach\n/Odour", "kod": None},
        {"row": 1, "param_name": "Wygląd\n/Appearance", "kod": None},
        {"row": 2, "param_name": "pH (10%, 25 C)", "kod": "ph_10proc"},
        {"row": 3, "param_name": "NaCl [%]", "kod": "nacl"},
        {"row": 4, "param_name": "Substancja aktywna [%]\n/Active matter [%]", "kod": "sa"},
        {"row": 5, "param_name": "Zawartość wolnego aminoamidu [%]\n/Free aminoamide [%]", "kod": "wolna_amina"},
        {"row": 6, "param_name": "Barwa w skali jodowej\n/Colour (Iodine scale)", "kod": "barwa_hz"},
        {"row": 7, "param_name": "MCA [ppm]", "kod": None},
        {"row": 8, "param_name": "DCA [ppm]", "kod": None},
        {"row": 9, "param_name": "DMAPA [ppm]", "kod": None},
    ],
    "REVADA Świadectwo_Certificate- Chegina KK WZÓR.docx": [
        {"row": 0, "param_name": "Zapach\n/Odour", "kod": None},
        {"row": 1, "param_name": "Wygląd\n/Appearance", "kod": None},
        {"row": 2, "param_name": "pH (10%, 25 C)", "kod": "ph_10proc"},
        {"row": 3, "param_name": "NaCl [%]", "kod": "nacl"},
        {"row": 4, "param_name": "Substancja aktywna [%]\n/Active matter [%]", "kod": "sa"},
        {"row": 5, "param_name": "Zawartość wolnego aminoamidu [%]\n/Free aminoamide [%]", "kod": "wolna_amina"},
        {"row": 6, "param_name": "Barwa w skali jodowej\n/Colour (Iodine scale)", "kod": "barwa_hz"},
        {"row": 7, "param_name": "MCA [ppm]", "kod": None},
        {"row": 8, "param_name": "DCA [ppm]", "kod": None},
        {"row": 9, "param_name": "DMAPA [ppm]", "kod": None},
    ],
    "Świadectwo-Certificate - Chemal CS 30 70 MB WZÓR.docx": [
        {"row": 0, "param_name": "Liczba hydroksylowa [mg KOH/g] / Hydroxyl number [mg KOH/g]", "kod": "lh"},
        {"row": 1, "param_name": "Liczba kwasowa [mg KOH/g]\n/Acid value [mg KOH/g]", "kod": "lk"},
        {"row": 2, "param_name": "Liczba zmydlenia [mg KOH/g]\n/Saponification value [mg KOH/g]", "kod": "lz"},
        {"row": 3, "param_name": "Liczba jodowa [g I2/100g]\n/Iodine value [g I2/100g]", "kod": "li"},
        {"row": 4, "param_name": "%C16", "kod": None},
        {"row": 5, "param_name": "%C18", "kod": None},
    ],
    "Świadectwo-Certificate - Chemal CS 30 70 WZÓR numer zamówienia.docx": [
        {"row": 0, "param_name": "Liczba hydroksylowa [mg KOH/g] / Hydroxyl number [mg KOH/g]", "kod": "lh"},
        {"row": 1, "param_name": "Liczba kwasowa [mg KOH/g]\n/Acid value [mg KOH/g]", "kod": "lk"},
        {"row": 2, "param_name": "Liczba zmydlenia [mg KOH/g]\n/Saponification value [mg KOH/g]", "kod": "lz"},
        {"row": 3, "param_name": "Liczba jodowa [g I2/100g]\n/Iodine value [g I2/100g]", "kod": "li"},
        {"row": 4, "param_name": "%C16", "kod": None},
        {"row": 5, "param_name": "%C18", "kod": None},
    ],
    "Świadectwo-Certificate - Chemal CS 30 70 WZÓR.docx": [
        {"row": 0, "param_name": "Liczba hydroksylowa [mg KOH/g] / Hydroxyl number [mg KOH/g]", "kod": "lh"},
        {"row": 1, "param_name": "Liczba kwasowa [mg KOH/g]\n/Acid value [mg KOH/g]", "kod": "lk"},
        {"row": 2, "param_name": "Liczba zmydlenia [mg KOH/g]\n/Saponification value [mg KOH/g]", "kod": "lz"},
        {"row": 3, "param_name": "Liczba jodowa [g I2/100g]\n/Iodine value [g I2/100g]", "kod": "li"},
        {"row": 4, "param_name": "%C16", "kod": None},
        {"row": 5, "param_name": "%C18", "kod": None},
    ],
    "Świadectwo-Certificate - Chemal CS 50 50 MB WZÓR.docx": [
        {"row": 0, "param_name": "Liczba hydroksylowa [mg KOH/g] / Hydroxyl number [mg KOH/g]", "kod": "lh"},
        {"row": 1, "param_name": "Liczba kwasowa [mg KOH/g]\n/Acid value [mg KOH/g]", "kod": "lk"},
        {"row": 2, "param_name": "Liczba zmydlenia [mg KOH/g]\n/Saponification value [mg KOH/g]", "kod": "lz"},
        {"row": 3, "param_name": "Liczba jodowa [g I2/100g]\n/Iodine value [g I2/100g]", "kod": "li"},
        {"row": 4, "param_name": "%C16", "kod": None},
        {"row": 5, "param_name": "%C18", "kod": None},
    ],
    "Świadectwo-Certificate - HSH CS 30 70 MB WZÓR.docx": [
        {"row": 0, "param_name": "Liczba hydroksylowa [mg KOH/g] / Hydroxyl number [mg KOH/g]", "kod": "lh"},
        {"row": 1, "param_name": "Liczba kwasowa [mg KOH/g]\n/Acid value [mg KOH/g]", "kod": "lk"},
        {"row": 2, "param_name": "Liczba zmydlenia [mg KOH/g]\n/Saponification value [mg KOH/g]", "kod": "lz"},
        {"row": 3, "param_name": "Liczba jodowa [g I2/100g]\n/Iodine value [g I2/100g]", "kod": "li"},
        {"row": 4, "param_name": "%C16", "kod": None},
        {"row": 5, "param_name": "%C18", "kod": None},
    ],
    "Świadectwo-Certificate - HSH CS 30 70 WZÓR.docx": [
        {"row": 0, "param_name": "Liczba hydroksylowa [mg KOH/g] / Hydroxyl number [mg KOH/g]", "kod": "lh"},
        {"row": 1, "param_name": "Liczba kwasowa [mg KOH/g]\n/Acid value [mg KOH/g]", "kod": "lk"},
        {"row": 2, "param_name": "Liczba zmydlenia [mg KOH/g]\n/Saponification value [mg KOH/g]", "kod": "lz"},
        {"row": 3, "param_name": "Liczba jodowa [g I2/100g]\n/Iodine value [g I2/100g]", "kod": "li"},
        {"row": 4, "param_name": "%C16", "kod": None},
        {"row": 5, "param_name": "%C18", "kod": None},
    ],
    "Świadectwo-Certificate - SLES WZÓR.docx": [
        {"row": 0, "param_name": "Barwa/Colour", "kod": None},
        {"row": 1, "param_name": "pH (3%, aq)", "kod": "ph_10proc"},
        {"row": 2, "param_name": "Substancja aktywna\n/Active matter [%]", "kod": "sa"},
    ],
    "Świadectwo-Certificate -Glikoster P WZÓR.docx": [
        {"row": 0, "param_name": "Barwa w skali jodowej\n/ Colour (Iodine scale)", "kod": "barwa_hz"},
        {"row": 1, "param_name": "Zapach\n/Odour", "kod": None},
        {"row": 2, "param_name": "Wygląd\n/ Appearance", "kod": None},
        {"row": 3, "param_name": "Liczba kwasowa [mg KOH/g]\n/Acid value [mg KOH/g]", "kod": "lk"},
        {"row": 4, "param_name": "Wolny glikol [%]\n/Free glycol [%]", "kod": "wolny_glikol"},
        {"row": 5, "param_name": "Liczba hydroksylowa\n[mg KOH/g]\n/Hydroxyl value [mg KOH/g]", "kod": "lh"},
        {"row": 6, "param_name": "Monoestry [%]\n/Monoesters [%]", "kod": "monoestry"},
        {"row": 7, "param_name": "%C14:0\n%C16:0\n%C18:0&C18:1", "kod": None},
    ],
    "ŚwiadectwoCertificate-Chegina K40 GL WZÓR ADAM&PARTNER.docx": [
        {"row": 0, "param_name": "Sucha masa [%]\n/Dry matter [%]", "kod": "sm"},
        {"row": 1, "param_name": "NaCl [%]", "kod": "nacl"},
        {"row": 2, "param_name": "Bawa w skali Hazena\n/Colour (Hazen scale)", "kod": "barwa_hz"},
        {"row": 3, "param_name": "pH (10%, aq)", "kod": "ph_10proc"},
        {"row": 4, "param_name": "Substancja aktywna [%]\n/Active matter [%]", "kod": "sa"},
        {"row": 5, "param_name": "Nadtlenki w przeliczeniu na H2O2 [%]\n/Peroxides as H2O2 [%]", "kod": "h2o2"},
    ],
    "ŚwiadectwoCertificate-Chegina K40 GL WZÓR NUMER ZAMÓWIENIA.docx": [
        {"row": 0, "param_name": "Sucha masa [%]\n/Dry matter [%]", "kod": "sm"},
        {"row": 1, "param_name": "NaCl [%]", "kod": "nacl"},
        {"row": 2, "param_name": "Barwa w skali Hazena\n/Colour (Hazen scale)", "kod": "barwa_hz"},
        {"row": 3, "param_name": "pH (10%, aq)", "kod": "ph_10proc"},
        {"row": 4, "param_name": "Substancja aktywna [%]\n/Active matter [%]", "kod": "sa"},
    ],
    "ŚwiadectwoCertificate-Chegina K40 GL wzór nr zam.docx": [
        {"row": 0, "param_name": "Sucha masa [%]\n/Dry matter [%]", "kod": "sm"},
        {"row": 1, "param_name": "NaCl [%]", "kod": "nacl"},
        {"row": 2, "param_name": "Barwa w skali Hazena\n/Colour (Hazen scale)", "kod": "barwa_hz"},
        {"row": 3, "param_name": "pH (10%, aq)", "kod": "ph_10proc"},
        {"row": 4, "param_name": "Substancja aktywna [%]\n/Active matter [%]", "kod": "sa"},
    ],
    "Świadectwo_Certificate - Alkinol  MB WZÓR.docx": [
        {"row": 0, "param_name": "Barwa w skali jodowej\n/Colour (Iodine scale)", "kod": "barwa_hz"},
        {"row": 1, "param_name": "Zapach\n/Odour", "kod": None},
        {"row": 2, "param_name": "Wygląd\n/Appearance", "kod": None},
        {"row": 3, "param_name": "Liczba kwasowa [mg KOH/g]\n/Acid value [mg KOH/g]", "kod": "lk"},
        {"row": 4, "param_name": "Liczba zmydlania [mg KOH/g]\n/Saponification value [mg KOH/g]", "kod": "lz"},
        {"row": 5, "param_name": "Temperatura krzepnięcia [C]\n/ Melting point [C]", "kod": None},
        {"row": 6, "param_name": "Liczba hydroksylowa [mg KOH/g]\n/Hydroxyl value [mg KOH/g]", "kod": "lh"},
    ],
    "Świadectwo_Certificate - Alkinol B MB WZÓR.docx": [
        {"row": 0, "param_name": "Barwa w skali jodowej\n/Colour (Iodine scale)", "kod": "barwa_hz"},
        {"row": 1, "param_name": "Zapach/Odour", "kod": None},
        {"row": 2, "param_name": "Wygląd/ Appearance", "kod": None},
        {"row": 3, "param_name": "Liczba kwasowa [mgKOH/g]\n/Acid value [mg KOH/g]", "kod": "lk"},
        {"row": 4, "param_name": "Liczba zmydlania [mgKOH/g[\n/Saponification value [mg KOH/g]", "kod": "lz"},
        {"row": 5, "param_name": "Temperatura kroplenia [C]\n/Dropping point [C]", "kod": None},
        {"row": 6, "param_name": "Liczba hydroksylowa [mg KOH/g]\n/Hydroxyl value [mg KOH/g]", "kod": "lh"},
        {"row": 7, "param_name": "Liczba jodowa [g I2/100 g]\n/Iodine value [g I2/100 g]", "kod": "li"},
    ],
    "Świadectwo_Certificate - Alkinol B WZÓR.docx": [
        {"row": 0, "param_name": "Barwa w skali jodowej\n/Colour (Iodine scale)", "kod": "barwa_hz"},
        {"row": 1, "param_name": "Zapach/Odour", "kod": None},
        {"row": 2, "param_name": "Wygląd/ Appearance", "kod": None},
        {"row": 3, "param_name": "Liczba kwasowa [mgKOH/g]\n/Acid value [mg KOH/g]", "kod": "lk"},
        {"row": 4, "param_name": "Liczba zmydlania [mgKOH/g[\n/Saponification value [mg KOH/g]", "kod": "lz"},
        {"row": 5, "param_name": "Temperatura kroplenia [C]\n/Dropping point [C]", "kod": None},
        {"row": 6, "param_name": "Liczba hydroksylowa [mg KOH/g]\n/Hydroxyl value [mg KOH/g]", "kod": "lh"},
        {"row": 7, "param_name": "Liczba jodowa [g I2/100 g]\n/Iodine value [g I2/100 g]", "kod": "li"},
    ],
    "Świadectwo_Certificate - Chegina GLOL40     WZÓR.docx": [
        {"row": 0, "param_name": "Barwa\n/Colour", "kod": None},
        {"row": 1, "param_name": "Zapach\n/Odour", "kod": None},
        {"row": 2, "param_name": "Wygląd\n/Appearance", "kod": None},
        {"row": 3, "param_name": "pH", "kod": "ph_10proc"},
        {"row": 4, "param_name": "Substancja aktywna [%]\n/Active matter [%]", "kod": "sa"},
        {"row": 5, "param_name": "NaCl [%]", "kod": "nacl"},
        {"row": 6, "param_name": "H2O [%]", "kod": None},
        {"row": 7, "param_name": "Wolna kokamidopropylodimetyloamina [%]\n/Free cocamidopropyldimethylamine [%]", "kod": "wolna_amina"},
    ],
    "Świadectwo_Certificate Alstermid-WZÓR.docx": [
        {"row": 0, "param_name": "Liczba kwasowa [mg KOH/g]\n/Acid value [mg KOH/g]", "kod": "lk"},
        {"row": 1, "param_name": "Liczba aminowa [mg KOH/g]\n/Amine value [mg/KOH/g]", "kod": "la"},
    ],
    "Świadectwo_Certificate- Chegina GLOL40 MB WZÓR OQEMA.docx": [
        {"row": 0, "param_name": "Barwa\n/Colour", "kod": None},
        {"row": 1, "param_name": "Zapach\n/Odour", "kod": None},
        {"row": 2, "param_name": "Wygląd\n/Appearance", "kod": None},
        {"row": 3, "param_name": "pH", "kod": "ph_10proc"},
        {"row": 4, "param_name": "Substancja aktywna [%]\n/Active matter [%]", "kod": "sa"},
        {"row": 5, "param_name": "NaCl [%]", "kod": "nacl"},
        {"row": 6, "param_name": "H2O [%]", "kod": None},
        {"row": 7, "param_name": "Wolna kokamidopropylodimetyloamina [%]\n/Free cocamidopropyldimethylamine [%]", "kod": "wolna_amina"},
    ],
    "Świadectwo_Certificate- Chegina GLOL40 MB WZÓR.docx": [
        {"row": 0, "param_name": "Barwa\n/Colour", "kod": None},
        {"row": 1, "param_name": "Zapach\n/Odour", "kod": None},
        {"row": 2, "param_name": "Wygląd\n/Appearance", "kod": None},
        {"row": 3, "param_name": "pH", "kod": "ph_10proc"},
        {"row": 4, "param_name": "Substancja aktywna [%]\n/Active matter [%]", "kod": "sa"},
        {"row": 5, "param_name": "NaCl [%]", "kod": "nacl"},
        {"row": 6, "param_name": "H2O [%]", "kod": None},
        {"row": 7, "param_name": "Wolna kokamidopropylodimetyloamina [%]\n/Free cocamidopropyldimethylamine [%]", "kod": "wolna_amina"},
    ],
    "Świadectwo_Certificate- Chegina GLOL40 nr zamówienia WZÓR.docx": [
        {"row": 0, "param_name": "Barwa\n/Colour", "kod": None},
        {"row": 1, "param_name": "Zapach\n/Odour", "kod": None},
        {"row": 2, "param_name": "Wygląd\n/Appearance", "kod": None},
        {"row": 3, "param_name": "pH", "kod": "ph_10proc"},
        {"row": 4, "param_name": "Substancja aktywna [%]\n/Active matter [%]", "kod": "sa"},
        {"row": 5, "param_name": "NaCl [%]", "kod": "nacl"},
        {"row": 6, "param_name": "H2O [%]", "kod": None},
        {"row": 7, "param_name": "Wolna kokamidopropylodimetyloamina [%]\n/Free cocamidopropyldimethylamine [%]", "kod": "wolna_amina"},
    ],
    "Świadectwo_Certificate- Chegina K40GLN MB WZÓR.docx": [
        {"row": 0, "param_name": "Barwa w skali Hazena/\nColour (Hazen scale)", "kod": "barwa_hz"},
        {"row": 1, "param_name": "Zapach/Odour", "kod": None},
        {"row": 2, "param_name": "Wygląd/Appearance", "kod": None},
        {"row": 3, "param_name": "pH (20°C)", "kod": "ph_10proc"},
        {"row": 4, "param_name": "Substancja aktywna [%]\n/Active matter [%]", "kod": "sa"},
        {"row": 5, "param_name": "NaCl [%]", "kod": "nacl"},
        {"row": 6, "param_name": "Sucha masa [%]\n/Dry matter [%]", "kod": "sm"},
        {"row": 7, "param_name": "H2O [%]", "kod": None},
        {"row": 8, "param_name": "Zawartość wolnego aminoamidu [%]\n/Free aminoamide [%]", "kod": "wolna_amina"},
    ],
    "Świadectwo_Certificate- Chegina K40GLN WZÓR.docx": [
        {"row": 0, "param_name": "Barwa w skali Hazena/\nColour (Hazen scale)", "kod": "barwa_hz"},
        {"row": 1, "param_name": "Zapach/Odour", "kod": None},
        {"row": 2, "param_name": "Wygląd/Appearance", "kod": None},
        {"row": 3, "param_name": "pH (20°C)", "kod": "ph_10proc"},
        {"row": 4, "param_name": "Substancja aktywna [%]\n/Active matter [%]", "kod": "sa"},
        {"row": 5, "param_name": "NaCl [%]", "kod": "nacl"},
        {"row": 6, "param_name": "Sucha masa [%]\n/Dry matter [%]", "kod": "sm"},
        {"row": 7, "param_name": "H2O [%]", "kod": None},
        {"row": 8, "param_name": "Zawartość wolnego aminoamidu [%]\n/Free aminoamide [%]", "kod": "wolna_amina"},
    ],
    "Świadectwo_Certificate- Chegina K40GLOL HQ WZÓR.docx": [
        {"row": 0, "param_name": "Barwa w skali Hazena\n/Colour (Hazen scale)", "kod": "barwa_hz"},
        {"row": 1, "param_name": "Zapach\n/Odour", "kod": None},
        {"row": 2, "param_name": "Wygląd\n/Appearance", "kod": None},
        {"row": 3, "param_name": "pH (20°C)", "kod": "ph_10proc"},
        {"row": 4, "param_name": "Substancja aktywna [%]\n/Active matter [%]", "kod": "sa"},
        {"row": 5, "param_name": "NaCl [%]", "kod": "nacl"},
        {"row": 6, "param_name": "Sucha masa [%]\n/Dry matter [%]", "kod": "sm"},
        {"row": 7, "param_name": "H2O [%]", "kod": None},
        {"row": 8, "param_name": "Wolna kokamidopropylodimetyloamina [%]\n/Free cocamidopropyldimethylamine [%]", "kod": "wolna_amina"},
    ],
    "Świadectwo_Certificate- Chegina K40GLOL MB   Kosmepol    WZÓR.docx": [
        {"row": 0, "param_name": "Barwa\n/Colour", "kod": None},
        {"row": 1, "param_name": "Zapach\n/Odour", "kod": None},
        {"row": 2, "param_name": "Wygląd\n/Appearance", "kod": None},
        {"row": 3, "param_name": "pH", "kod": "ph_10proc"},
        {"row": 4, "param_name": "Substancja aktywna [%]\n/Active matter [%]", "kod": "sa"},
        {"row": 5, "param_name": "NaCl [%]", "kod": "nacl"},
        {"row": 6, "param_name": "H2O [%]", "kod": None},
        {"row": 7, "param_name": "Wolna kokamidopropylodimetyloamina [%]\n/Free cocamidopropyldimethylamine [%]", "kod": "wolna_amina"},
    ],
    "Świadectwo_Certificate- Chegina K40GLOL MB WZÓR Loreal Belgia.docx": [
        {"row": 0, "param_name": "Barwa\n/Colour", "kod": None},
        {"row": 1, "param_name": "Zapach\n/Odour", "kod": None},
        {"row": 2, "param_name": "Wygląd\n/Appearance", "kod": None},
        {"row": 3, "param_name": "pH", "kod": "ph_10proc"},
        {"row": 4, "param_name": "Substancja aktywna [%]\n/Active matter [%]", "kod": "sa"},
        {"row": 5, "param_name": "NaCl [%]", "kod": "nacl"},
        {"row": 6, "param_name": "H2O [%]", "kod": None},
        {"row": 7, "param_name": "Wolna kokamidopropylodimetyloamina [%]\n/Free cocamidopropyldimethylamine [%]", "kod": "wolna_amina"},
    ],
    "Świadectwo_Certificate- Chegina K40GLOL MB WZÓR Loreal Włochy.docx": [
        {"row": 0, "param_name": "Barwa\n/Colour", "kod": None},
        {"row": 1, "param_name": "Zapach\n/Odour", "kod": None},
        {"row": 2, "param_name": "Wygląd\n/Appearance", "kod": None},
        {"row": 3, "param_name": "pH", "kod": "ph_10proc"},
        {"row": 4, "param_name": "Substancja aktywna [%]\n/Active matter [%]", "kod": "sa"},
        {"row": 5, "param_name": "NaCl [%]", "kod": "nacl"},
        {"row": 6, "param_name": "H2O [%]", "kod": None},
        {"row": 7, "param_name": "Wolna kokamidopropylodimetyloamina [%]\n/Free cocamidopropyldimethylamine [%]", "kod": "wolna_amina"},
    ],
    "Świadectwo_Certificate- Chegina K40GLOL MB WZÓR Loreal.docx": [
        {"row": 0, "param_name": "Barwa\n/Colour", "kod": None},
        {"row": 1, "param_name": "Zapach\n/Odour", "kod": None},
        {"row": 2, "param_name": "Wygląd\n/Appearance", "kod": None},
        {"row": 3, "param_name": "pH", "kod": "ph_10proc"},
        {"row": 4, "param_name": "Substancja aktywna [%]\n/Active matter [%]", "kod": "sa"},
        {"row": 5, "param_name": "NaCl [%]", "kod": "nacl"},
        {"row": 6, "param_name": "H2O [%]", "kod": None},
        {"row": 7, "param_name": "Wolna kokamidopropylodimetyloamina [%]\n/Free cocamidopropyldimethylamine [%]", "kod": "wolna_amina"},
    ],
    "Świadectwo_Certificate- Chegina K40GLOS MB WZÓR.docx": [
        {"row": 0, "param_name": "Barwa w skali Hazena/\nColour (Hazen scale)", "kod": "barwa_hz"},
        {"row": 1, "param_name": "Zapach/Odour", "kod": None},
        {"row": 2, "param_name": "Wygląd/Appearance", "kod": None},
        {"row": 3, "param_name": "pH (20°C)", "kod": "ph_10proc"},
        {"row": 4, "param_name": "Substancja aktywna [%]\n/Active matter [%]", "kod": "sa"},
        {"row": 5, "param_name": "NaCl [%]", "kod": "nacl"},
        {"row": 6, "param_name": "Sucha masa [%]\n/Dry matter [%]", "kod": "sm"},
        {"row": 7, "param_name": "H2O [%]", "kod": None},
        {"row": 8, "param_name": "Wolna kokamidopropylodimetyloamina [%]\n/Free cocamidopropyldimethylamine [%]", "kod": "wolna_amina"},
    ],
    "Świadectwo_Certificate- Chegina K40GLOS WZÓR.docx": [
        {"row": 0, "param_name": "Barwa w skali Hazena/\nColour (Hazen scale)", "kod": "barwa_hz"},
        {"row": 1, "param_name": "Zapach/Odour", "kod": None},
        {"row": 2, "param_name": "Wygląd/Appearance", "kod": None},
        {"row": 3, "param_name": "pH (20°C)", "kod": "ph_10proc"},
        {"row": 4, "param_name": "Substancja aktywna [%]\n/Active matter [%]", "kod": "sa"},
        {"row": 5, "param_name": "NaCl [%]", "kod": "nacl"},
        {"row": 6, "param_name": "Sucha masa [%]\n/Dry matter [%]", "kod": "sm"},
        {"row": 7, "param_name": "H2O [%]", "kod": None},
        {"row": 8, "param_name": "Wolna kokamidopropylodimetyloamina [%]\n/Free cocamidopropyldimethylamine [%]", "kod": "wolna_amina"},
    ],
    "Świadectwo_Certificate- Chegina KK  SKINCHEM - WZÓR.docx": [
        {"row": 0, "param_name": "Zapach\n/Odour", "kod": None},
        {"row": 1, "param_name": "Wygląd\n/Appearance", "kod": None},
        {"row": 2, "param_name": "pH (10%, 25 C)", "kod": "ph_10proc"},
        {"row": 3, "param_name": "NaCl [%]", "kod": "nacl"},
        {"row": 4, "param_name": "Substancja aktywna [%]\n/Active matter [%]", "kod": "sa"},
        {"row": 5, "param_name": "Zawartość wolnego aminoamidu [%]\n/Free aminoamide [%]", "kod": "wolna_amina"},
        {"row": 6, "param_name": "Barwa w skali jodowej\n/Colour (Iodine scale)", "kod": "barwa_hz"},
        {"row": 7, "param_name": "MCA [ppm]", "kod": None},
        {"row": 8, "param_name": "DCA [ppm]", "kod": None},
        {"row": 9, "param_name": "DMAPA [ppm]", "kod": None},
    ],
    "Świadectwo_Certificate-Alkinol WZÓR.docx": [
        {"row": 0, "param_name": "Barwa w skali jodowej\n/Colour (Iodine scale)", "kod": "barwa_hz"},
        {"row": 1, "param_name": "Zapach\n/Odour", "kod": None},
        {"row": 2, "param_name": "Wygląd\n/Appearance", "kod": None},
        {"row": 3, "param_name": "Liczba kwasowa [mg KOH/g]\n/Acid value [mg KOH/g]", "kod": "lk"},
        {"row": 4, "param_name": "Liczba zmydlania [mg KOH/g]\n/Saponification value [mg KOH/g]", "kod": "lz"},
        {"row": 5, "param_name": "Temperatura kroplenia [C]\n/Dropping point [C]", "kod": None},
        {"row": 6, "param_name": "Liczba hydroksylowa [mg KOH/g]\n/Hydroxyl value [mg KOH/g]", "kod": "lh"},
    ],
    "Świadectwo_Certificate-Alstermid K WZÓR.docx": [
        {"row": 0, "param_name": "Liczba kwasowa [mg KOH/g]\n/Acid value [mg KOH/g]", "kod": "lk"},
        {"row": 1, "param_name": "Wolne kwasy tłuszczowe \n(kwasy kokosowe, MW=220) [%]\n/Free fatty acids \n(Coconut fatty acids, MW=220) [%]", "kod": "wkt"},
        {"row": 2, "param_name": "Liczba aminowa [mg KOH/g]\n/Amine value [mg KOH/g]", "kod": "la"},
        {"row": 3, "param_name": "Barwa w skali jodowej\n/Colour (Iodine scale)", "kod": "barwa_hz"},
    ],
    "Świadectwo_Certificate-Chegina K40 GLO               WZÓR.docx": [
        {"row": 0, "param_name": "Sucha masa [%]\n/Dry matter [%]", "kod": "sm"},
        {"row": 1, "param_name": "NaCl [%]", "kod": "nacl"},
        {"row": 2, "param_name": "Barwa w skali Hazena\n/Colour (Hazen scale)", "kod": "barwa_hz"},
        {"row": 3, "param_name": "pH (10%, aq)", "kod": "ph_10proc"},
        {"row": 4, "param_name": "Substancja aktywna [%]\n/Active matter [%]", "kod": "sa"},
        {"row": 5, "param_name": "Gęstość (20°C) [g/cm3]\n/Density (20°C) [g/cm3]", "kod": "gestosc"},
    ],
    "Świadectwo_Certificate-Chegina K40 GLO MB WZÓR.docx": [
        {"row": 0, "param_name": "Sucha masa [%]\n/Dry matter [%]", "kod": "sm"},
        {"row": 1, "param_name": "NaCl [%]", "kod": "nacl"},
        {"row": 2, "param_name": "Barwa w skali Hazena\n/Colour (Hazen scale)", "kod": "barwa_hz"},
        {"row": 3, "param_name": "pH (10%, aq)", "kod": "ph_10proc"},
        {"row": 4, "param_name": "Substancja aktywna [%]\n/Active matter [%]", "kod": "sa"},
        {"row": 5, "param_name": "Gęstość (20°C) [g/cm3]\n/Density (20°C) [g/cm3]", "kod": "gestosc"},
    ],
    "Świadectwo_Certificate-Chegina K40GL MB WZÓR.docx": [
        {"row": 0, "param_name": "Sucha masa [%]\n/Dry matter [%]", "kod": "sm"},
        {"row": 1, "param_name": "NaCl [%]", "kod": "nacl"},
        {"row": 2, "param_name": "Barwa w skali Hazena\n/Colour (Hazen scale)", "kod": "barwa_hz"},
        {"row": 3, "param_name": "pH (10%, aq)", "kod": "ph_10proc"},
        {"row": 4, "param_name": "Substancja aktywna [%]\n/Active matter [%]", "kod": "sa"},
    ],
    "Świadectwo_Certificate-Chegina K40GL WZÓR.docx": [
        {"row": 0, "param_name": "Sucha masa [%]\n/Dry matter [%]", "kod": "sm"},
        {"row": 1, "param_name": "NaCl [%]", "kod": "nacl"},
        {"row": 2, "param_name": "Barwa w skali Hazena\n/Colour (Hazen scale)", "kod": "barwa_hz"},
        {"row": 3, "param_name": "pH (10%, aq)", "kod": "ph_10proc"},
        {"row": 4, "param_name": "Substancja aktywna [%]\n/Active matter [%]", "kod": "sa"},
    ],
    "Świadectwo_Certificate-Chegina K40GLO MB WZÓR nr zamówienia.docx": [
        {"row": 0, "param_name": "Sucha masa [%]\n/Dry matter [%]", "kod": "sm"},
        {"row": 1, "param_name": "NaCl [%]", "kod": "nacl"},
        {"row": 2, "param_name": "Barwa w skali Hazena\n/Colour (Hazen scale)", "kod": "barwa_hz"},
        {"row": 3, "param_name": "pH (10%, aq)", "kod": "ph_10proc"},
        {"row": 4, "param_name": "Substancja aktywna [%]\n/Active matter [%]", "kod": "sa"},
    ],
    "Świadectwo_Certificate-Chegina K40GLO MB WZÓR.docx": [
        {"row": 0, "param_name": "Sucha masa [%]\n/Dry matter [%]", "kod": "sm"},
        {"row": 1, "param_name": "NaCl [%]", "kod": "nacl"},
        {"row": 2, "param_name": "Barwa w skali Hazena\n/Colour (Hazen scale)", "kod": "barwa_hz"},
        {"row": 3, "param_name": "pH (10%, aq)", "kod": "ph_10proc"},
        {"row": 4, "param_name": "Substancja aktywna [%]\n/Active matter [%]", "kod": "sa"},
    ],
    "Świadectwo_Certificate-Chegina K40GLO WZÓR z nr zamówienia.docx": [
        {"row": 0, "param_name": "Sucha masa [%]\n/Dry matter [%]", "kod": "sm"},
        {"row": 1, "param_name": "NaCl [%]", "kod": "nacl"},
        {"row": 2, "param_name": "Barwa w skali Hazena\n/Colour (Hazen scale)", "kod": "barwa_hz"},
        {"row": 3, "param_name": "pH (10%, aq)", "kod": "ph_10proc"},
        {"row": 4, "param_name": "Substancja aktywna [%]\n/Active matter [%]", "kod": "sa"},
    ],
    "Świadectwo_Certificate-Chegina K40GLO WZÓR.docx": [
        {"row": 0, "param_name": "Sucha masa [%]\n/Dry matter [%]", "kod": "sm"},
        {"row": 1, "param_name": "NaCl [%]", "kod": "nacl"},
        {"row": 2, "param_name": "Barwa w skali Hazena\n/Colour (Hazen scale)", "kod": "barwa_hz"},
        {"row": 3, "param_name": "pH (10%, aq)", "kod": "ph_10proc"},
        {"row": 4, "param_name": "Substancja aktywna [%]\n/Active matter [%]", "kod": "sa"},
    ],
    "Świadectwo_Certificate-Chegina K7 MB -WZÓR.docx": [
        {"row": 0, "param_name": "Sucha masa [%]\n/Dry matter [%]", "kod": "sm"},
        {"row": 1, "param_name": "NaCl [%]", "kod": "nacl"},
        {"row": 2, "param_name": "Wsp. załamania światła (nD20)\n/Refraction (nD20)", "kod": "nd20"},
        {"row": 3, "param_name": "Barwa w skali jodowej\n/Colour (Iodine scale)", "kod": "barwa_hz"},
        {"row": 4, "param_name": "pH (10%, aq)", "kod": "ph_10proc"},
        {"row": 5, "param_name": "Substancja aktywna [%]\n/Active matter [%]", "kod": "sa"},
    ],
    "Świadectwo_Certificate-Chegina K7 MB WZÓR  ADAM&PARTNER.docx": [
        {"row": 0, "param_name": "Sucha masa [%]\n/Dry matter [%]", "kod": "sm"},
        {"row": 1, "param_name": "NaCl [%]", "kod": "nacl"},
        {"row": 2, "param_name": "Wsp. załamania światła (nD20)\n/Refraction (nD20)", "kod": "nd20"},
        {"row": 3, "param_name": "Barwa w skali jodowej\n/Colour (Iodine scale)", "kod": "barwa_hz"},
        {"row": 4, "param_name": "pH (10%, aq)", "kod": "ph_10proc"},
        {"row": 5, "param_name": "Substancja aktywna [%]\n/Active matter [%]", "kod": "sa"},
        {"row": 6, "param_name": "Nadtlenki w przeliczeniu na H2O2 [%]\n/Peroxides as H2O2 [%]", "kod": "h2o2"},
    ],
    "Świadectwo_Certificate-Chegina K7 MB WZÓR DR. MIELE.docx": [
        {"row": 0, "param_name": "Sucha masa [%]\n/Dry matter [%]", "kod": "sm"},
        {"row": 1, "param_name": "NaCl [%]", "kod": "nacl"},
        {"row": 2, "param_name": "Wsp. załamania światła (nD20)\n/Refraction (nD20)", "kod": "nd20"},
        {"row": 3, "param_name": "Barwa w skali jodowej\n/Colour (Iodine scale)", "kod": "barwa_hz"},
        {"row": 4, "param_name": "pH (10%, aq)", "kod": "ph_10proc"},
        {"row": 5, "param_name": "Substancja aktywna [%]\n/Active matter [%]", "kod": "sa"},
    ],
    "Świadectwo_Certificate-Chegina K7 WZÓR ADAM&PARTNER.docx": [
        {"row": 0, "param_name": "Sucha masa [%]\n/Dry matter [%]", "kod": "sm"},
        {"row": 1, "param_name": "NaCl [%]", "kod": "nacl"},
        {"row": 2, "param_name": "Wsp. załamania światła (nD20)\n/Refraction (nD20)", "kod": "nd20"},
        {"row": 3, "param_name": "Barwa w skali jodowej\n/Colour (Iodine scale)", "kod": "barwa_hz"},
        {"row": 4, "param_name": "pH (10%, aq)", "kod": "ph_10proc"},
        {"row": 5, "param_name": "Substancja aktywna [%]\n/Active matter [%]", "kod": "sa"},
        {"row": 6, "param_name": "Nadtlenki w przeliczeniu na H2O2 [%]\n/Peroxides as H2O2 [%]", "kod": "h2o2"},
    ],
    "Świadectwo_Certificate-Chegina K7 WZÓR GLOBAL_DR. MIELE.docx": [
        {"row": 0, "param_name": "Sucha masa [%]\n/Dry matter [%]", "kod": "sm"},
        {"row": 1, "param_name": "NaCl [%]", "kod": "nacl"},
        {"row": 2, "param_name": "Wsp. załamania światła (nD20)\n/Refraction (nD20)", "kod": "nd20"},
        {"row": 3, "param_name": "Barwa w skali jodowej\n/Colour (Iodine scale)", "kod": "barwa_hz"},
        {"row": 4, "param_name": "pH (10%, aq)", "kod": "ph_10proc"},
        {"row": 5, "param_name": "Substancja aktywna [%]\n/Active matter [%]", "kod": "sa"},
    ],
    "Świadectwo_Certificate-Chegina K7 WZÓR nr zamówienia.docx": [
        {"row": 0, "param_name": "Sucha masa [%]\n/Dry matter [%]", "kod": "sm"},
        {"row": 1, "param_name": "NaCl [%]", "kod": "nacl"},
        {"row": 2, "param_name": "Wsp. załamania światła (nD20)\n/Refraction (nD20)", "kod": "nd20"},
        {"row": 3, "param_name": "Barwa w skali jodowej\n/Colour (Iodine scale)", "kod": "barwa_hz"},
        {"row": 4, "param_name": "pH (10%, aq)", "kod": "ph_10proc"},
        {"row": 5, "param_name": "Substancja aktywna [%]\n/Active matter [%]", "kod": "sa"},
    ],
    "Świadectwo_Certificate-Chegina K7 WZÓR.docx": [
        {"row": 0, "param_name": "Sucha masa [%]\n/Dry matter [%]", "kod": "sm"},
        {"row": 1, "param_name": "NaCl [%]", "kod": "nacl"},
        {"row": 2, "param_name": "Wsp. załamania światła (nD20)\n/Refraction (nD20)", "kod": "nd20"},
        {"row": 3, "param_name": "Barwa w skali jodowej\n/Colour (Iodine scale)", "kod": "barwa_hz"},
        {"row": 4, "param_name": "pH (10%, aq)", "kod": "ph_10proc"},
        {"row": 5, "param_name": "Substancja aktywna [%]\n/Active matter [%]", "kod": "sa"},
    ],
    "Świadectwo_Certificate-Chegina K7B MB -WZÓR.docx": [
        {"row": 0, "param_name": "Sucha masa [%]\n/Dry matter [%]", "kod": "sm"},
        {"row": 1, "param_name": "Barwa w skali jodowej\n/Colour (Iodine scale)", "kod": "barwa_hz"},
        {"row": 2, "param_name": "pH (10%, aq)", "kod": "ph_10proc"},
        {"row": 3, "param_name": "Substancja aktywna [%]\n/Active matter [%]", "kod": "sa"},
    ],
    "Świadectwo_Certificate-Chegina K7B WZÓR.docx": [
        {"row": 0, "param_name": "Sucha masa [%]\n/Dry matter [%]", "kod": "sm"},
        {"row": 1, "param_name": "Barwa w skali jodowej\n/Colour (Iodine scale)", "kod": "barwa_hz"},
        {"row": 2, "param_name": "pH (10%, aq)", "kod": "ph_10proc"},
        {"row": 3, "param_name": "Substancja aktywna [%]\n/Active matter [%]", "kod": "sa"},
    ],
    "Świadectwo_Certificate-Chegina KK wzór.docx": [
        {"row": 0, "param_name": "Zapach\n/Odour", "kod": None},
        {"row": 1, "param_name": "Wygląd\n/Appearance", "kod": None},
        {"row": 2, "param_name": "pH (10%, 25 C)", "kod": "ph_10proc"},
        {"row": 3, "param_name": "NaCl [%]", "kod": "nacl"},
        {"row": 4, "param_name": "Substancja aktywna [%]\n/Active matter [%]", "kod": "sa"},
        {"row": 5, "param_name": "Zawartość wolnego aminoamidu [%]\n/Free aminoamide [%]", "kod": "wolna_amina"},
        {"row": 6, "param_name": "Barwa w skali jodowej\n/Colour (Iodine scale)", "kod": "barwa_hz"},
        {"row": 7, "param_name": "MCA [ppm]", "kod": None},
        {"row": 8, "param_name": "DCA [ppm]", "kod": None},
        {"row": 9, "param_name": "DMAPA [ppm]", "kod": None},
    ],
    "Świadectwo_Certificate-Chegina KK wzór_bez kodu.docx": [
        {"row": 0, "param_name": "Zapach\n/Odour", "kod": None},
        {"row": 1, "param_name": "Wygląd\n/Appearance", "kod": None},
        {"row": 2, "param_name": "pH (10%, 25 C)", "kod": "ph_10proc"},
        {"row": 3, "param_name": "NaCl [%]", "kod": "nacl"},
        {"row": 4, "param_name": "Substancja aktywna [%]\n/Active matter [%]", "kod": "sa"},
        {"row": 5, "param_name": "Zawartość wolnego aminoamidu [%]\n/Free aminoamide [%]", "kod": "wolna_amina"},
        {"row": 6, "param_name": "Barwa w skali jodowej\n/Colour (Iodine scale)", "kod": "barwa_hz"},
    ],
    "Świadectwo_Certificate-Chegina WZÓR_ nr zamówienia.docx": [
        {"row": 0, "param_name": "Sucha masa [%]\n/Dry matter [%]", "kod": "sm"},
        {"row": 1, "param_name": "NaCl [%]", "kod": "nacl"},
        {"row": 2, "param_name": "Wsp. załamania światła (nD20)\n/Refraction (nD20)", "kod": "nd20"},
        {"row": 3, "param_name": "pH (10%, aq)", "kod": "ph_10proc"},
        {"row": 4, "param_name": "Barwa w skali jodowej\n/Colour (Iodine scale)", "kod": "barwa_hz"},
    ],
    "Świadectwo_Certificate-Chelamid DK                          WZÓR.docx": [
        {"row": 0, "param_name": "DEA  [%]", "kod": "dietanolamina"},
        {"row": 1, "param_name": "Barwa w skali jodowej\n/Colour (Iodine scale)", "kod": "barwa_hz"},
        {"row": 2, "param_name": "pH (1%, aq)", "kod": "ph_10proc"},
    ],
    "Świadectwo_Certificate-Chelamid DK                    WZÓR nr zam..docx": [
        {"row": 0, "param_name": "DEA  [%]", "kod": "dietanolamina"},
        {"row": 1, "param_name": "Barwa w skali jodowej\n/Colour (Iodine scale)", "kod": "barwa_hz"},
        {"row": 2, "param_name": "pH (1%, aq)", "kod": "ph_10proc"},
    ],
    "Świadectwo_Certificate-Chelamid DK                   WZÓR PEŁNA NR ZAM.docx": [
        {"row": 0, "param_name": "DEA  [%]", "kod": "dietanolamina"},
        {"row": 1, "param_name": "Barwa w skali jodowej\n/Colour (Iodine scale)", "kod": "barwa_hz"},
        {"row": 2, "param_name": "pH (1%, aq)", "kod": "ph_10proc"},
        {"row": 3, "param_name": "Dietanoloamid [%]\n/Diethanoloamide [%]", "kod": "dietanolamina"},
        {"row": 4, "param_name": "Glicerol [%]\n/Glycerol [%]", "kod": None},
        {"row": 5, "param_name": "Postać\n/Form", "kod": None},
    ],
    "Świadectwo_Certificate-Chelamid DK                   WZÓR_PEŁNA.docx": [
        {"row": 0, "param_name": "DEA  [%]", "kod": "dietanolamina"},
        {"row": 1, "param_name": "Barwa w skali jodowej\n/Colour (Iodine scale)", "kod": "barwa_hz"},
        {"row": 2, "param_name": "pH (1%, aq)", "kod": "ph_10proc"},
        {"row": 3, "param_name": "Dietanoloamid [%]\n/Diethanoloamide [%]", "kod": "dietanolamina"},
        {"row": 4, "param_name": "Glicerol [%]\n/Glycerol [%]", "kod": None},
        {"row": 5, "param_name": "Postać\n/Form", "kod": None},
    ],
    "Świadectwo_Certificate-Chelamid DK MB               WZÓR.docx": [
        {"row": 0, "param_name": "DEA [%]", "kod": "dietanolamina"},
        {"row": 1, "param_name": "Barwa w skali jodowej\n/Colour (Iodine scale)", "kod": "barwa_hz"},
        {"row": 2, "param_name": "pH (1%, aq)", "kod": "ph_10proc"},
        {"row": 3, "param_name": "Postać\n/Form", "kod": None},
    ],
    "Świadectwo_Certificate-Chelamid DK MB               nr zam. WZÓR.docx": [
        {"row": 0, "param_name": "DEA [%]", "kod": "dietanolamina"},
        {"row": 1, "param_name": "Barwa w skali jodowej\n/Colour (Iodine scale)", "kod": "barwa_hz"},
        {"row": 2, "param_name": "pH (1%, aq)", "kod": "ph_10proc"},
        {"row": 3, "param_name": "Postać\n/Form", "kod": None},
    ],
    "Świadectwo_Certificate-Chelamid DK MB Elin WZÓR.docx": [
        {"row": 0, "param_name": "DEA [%]", "kod": "dietanolamina"},
        {"row": 1, "param_name": "Barwa w skali jodowej\n/Colour (Iodine scale)", "kod": "barwa_hz"},
        {"row": 2, "param_name": "pH (1%, aq)", "kod": "ph_10proc"},
        {"row": 3, "param_name": "Dietanoloamid [%]\n/Diethanoloamide [%]", "kod": "dietanolamina"},
        {"row": 4, "param_name": "Postać\n/Form", "kod": None},
    ],
    "Świadectwo_Certificate-Cheminox K 35- WZÓR.docx": [
        {"row": 0, "param_name": "Sucha masa [%]\n/Dry matter [%]", "kod": "sm"},
        {"row": 1, "param_name": "Substancja aktywna [%]\n/Active matter [%]", "kod": "sa"},
        {"row": 2, "param_name": "pH (10%, aq)", "kod": "ph_10proc"},
        {"row": 3, "param_name": "H2O2 [%]", "kod": "h2o2"},
        {"row": 4, "param_name": "Barwa w skali jodowej\n/Colour (Iodine scale)", "kod": "barwa_hz"},
    ],
    "Świadectwo_Certificate-Cheminox K 35- WZÓR_nr zamówienia.docx": [
        {"row": 0, "param_name": "Sucha masa [%]\n/Dry matter [%]", "kod": "sm"},
        {"row": 1, "param_name": "Substancja aktywna [%]\n/Active matter [%]", "kod": "sa"},
        {"row": 2, "param_name": "pH (10%, aq)", "kod": "ph_10proc"},
        {"row": 3, "param_name": "H2O2 [%]", "kod": "h2o2"},
        {"row": 4, "param_name": "Barwa w skali jodowej\n/Colour (Iodine scale)", "kod": "barwa_hz"},
    ],
    "Świadectwo_Certificate-Cheminox K MB - WZÓR.docx": [
        {"row": 0, "param_name": "Sucha masa [%]\n/Dry matter [%]", "kod": "sm"},
        {"row": 1, "param_name": "Substancja aktywna [%]\n/Active matter [%]", "kod": "sa"},
        {"row": 2, "param_name": "pH (10%, aq)", "kod": "ph_10proc"},
        {"row": 3, "param_name": "H2O2 [%]", "kod": "h2o2"},
        {"row": 4, "param_name": "Barwa w skali jodowej\n/Colour (Iodine scale)", "kod": "barwa_hz"},
    ],
    "Świadectwo_Certificate-Cheminox K-                         WZÓR.docx": [
        {"row": 0, "param_name": "Sucha masa [%]\n/Dry matter [%]", "kod": "sm"},
        {"row": 1, "param_name": "pH (10%, aq)", "kod": "ph_10proc"},
        {"row": 2, "param_name": "H2O2 [%]", "kod": "h2o2"},
        {"row": 3, "param_name": "Barwa w skali jodowej\n/Colour (Iodine scale)", "kod": "barwa_hz"},
        {"row": 4, "param_name": "Gęstość (20°C) [g/cm3]\n/Density (20°C) [g/cm3]", "kod": "gestosc"},
    ],
    "Świadectwo_Certificate-Cheminox K- WZÓR NR ZAM..docx": [
        {"row": 0, "param_name": "Sucha masa [%]\n/Dry matter [%]", "kod": "sm"},
        {"row": 1, "param_name": "Subsancja aktywna [%]\n/Active matter [%]", "kod": "sa"},
        {"row": 2, "param_name": "pH (10%, aq)", "kod": "ph_10proc"},
        {"row": 3, "param_name": "H2O2 [%]", "kod": "h2o2"},
        {"row": 4, "param_name": "Barwa w skali jodowej\n/Colour (Iodine scale)", "kod": "barwa_hz"},
    ],
    "Świadectwo_Certificate-Cheminox K- WZÓR.docx": [
        {"row": 0, "param_name": "Sucha masa [%]\n/Dry matter [%]", "kod": "sm"},
        {"row": 1, "param_name": "Substancja aktywna [%]\n/Active matter [%]", "kod": "sa"},
        {"row": 2, "param_name": "pH (10%, aq)", "kod": "ph_10proc"},
        {"row": 3, "param_name": "H2O2 [%]", "kod": "h2o2"},
        {"row": 4, "param_name": "Barwa w skali jodowej\n/Colour (Iodine scale)", "kod": "barwa_hz"},
    ],
    "Świadectwo_Certificate-Citrowax WZÓR.docx": [
        {"row": 0, "param_name": "Liczba kwasowa [mg KOH/g]\n/Acid value [mg KOH/g]", "kod": "lk"},
        {"row": 1, "param_name": "Temperatura kroplenia [0C]\n/Dropping point [0C]", "kod": None},
    ],
    "Świadectwo_Certificate-Dister E WZÓR.docx": [
        {"row": 0, "param_name": "Liczba kwasowa [mg KOH/g]\n/Acid value [mg KOH/g]", "kod": "lk"},
        {"row": 1, "param_name": "Wolny glikol etylenowy [%]\n/Free ethylene glycol [%]", "kod": "wolny_glikol"},
        {"row": 2, "param_name": "Liczba hydroksylowa [mg KOH/g]\n/Hydroxyl value [mg KOH/g]", "kod": "lh"},
        {"row": 3, "param_name": "Liczba zmydlenia [mg KOH/g]\n/Saponification value [mg KOH/g]", "kod": "lz"},
        {"row": 4, "param_name": "Temperatura topnienia [°C]\n/Melting point [°C]", "kod": None},
    ],
    "Świadectwo_Certificate-Kw. Stearynowy WZÓR.docx": [
        {"row": 0, "param_name": "Liczba kwasowa [mg KOH/g]\n/Acid value [mg KOH/g]", "kod": "lk"},
        {"row": 1, "param_name": "Temperatura kroplenia [C]\n/Dropping point [C]", "kod": None},
        {"row": 2, "param_name": "Liczba jodowa, [g I2/100 g]\n/Iodine value [g I2/100 g]", "kod": "li"},
    ],
    "Świadectwo_Certificate-Monamid K WZÓR.docx": [
        {"row": 0, "param_name": "Barwa w skali jodowej\n/Colour (Iodine scale)", "kod": "barwa_hz"},
        {"row": 1, "param_name": "Wolne kwasy tłuszczowe [%]\nw przeliczeniu na kwas laurynowy \n(MW = 200,3 g/mol)\n/Free fatty acids [%] as lauric acid, (MW = 200,3 g/mol)", "kod": "wkt"},
        {"row": 2, "param_name": "MEA [%] (MW = 61,1 g/mol)", "kod": "mea"},
        {"row": 3, "param_name": "Estry [%] w przeliczeniu na laurynian metylu\n/Esters [%] as methyl laurate,\n(MW=214 g/mol)", "kod": "estry"},
    ],
    "Świadectwo_Certificate-Monamid KO AVON WZÓR.docx": [
        {"row": 0, "param_name": "Barwa w skali Gardnera\n/Colour (Gardner scale)", "kod": "barwa_hz"},
        {"row": 1, "param_name": "Zapach\n/Odour", "kod": None},
        {"row": 2, "param_name": "Wygląd\n/Appearance", "kod": None},
        {"row": 3, "param_name": "Wolne kwasy tłuszczowe [%]\nw przeliczeniu na kwas laurynowy \n(M = 200,3 g/mol)\n/Free fatty acids [%] as lauric acid, (MW = 200,3 g/mol)", "kod": "wkt"},
        {"row": 4, "param_name": "MEA [%]  (M/MW = 61,1 g/mol)", "kod": "mea"},
        {"row": 5, "param_name": "Estry [%]/Esters [%]", "kod": "estry"},
        {"row": 6, "param_name": "Gliceryna [%]/Glycerine [%]", "kod": None},
        {"row": 7, "param_name": "Rozkład kwasów tłuszczowych [%]/\nFatty acid distribution [%]\n≤C6:0\nC8:0\nC10:0\nC12:0\nC14:0\nC16:0\nC18:0\nC18:1\nC18:2", "kod": None},
    ],
    "Świadectwo_Certificate-Monamid KO GHP WZÓR.docx": [
        {"row": 0, "param_name": "Barwa w skali Gardnera\n/Colour (Gardner scale)", "kod": "barwa_hz"},
        {"row": 1, "param_name": "Zapach\n/Odour", "kod": None},
        {"row": 2, "param_name": "Wygląd\n/Appearance", "kod": None},
        {"row": 3, "param_name": "Wolne kwasy tłuszczowe [%]\nw przeliczeniu na kwas laurynowy \n(M = 200,3 g/mol)\n/Free fatty acids [%] as lauric acid, (M = 200,3 g/mol)", "kod": "wkt"},
        {"row": 4, "param_name": "MEA [%]  (M = 61,1 g/mol)", "kod": "mea"},
        {"row": 5, "param_name": "Estry [%]\n/Esters [%]", "kod": "estry"},
    ],
    "Świadectwo_Certificate-Monamid KO Hal WZÓR.docx": [
        {"row": 0, "param_name": "Barwa w skali Gardnera\n/Colour (Gardner scale)", "kod": "barwa_hz"},
        {"row": 1, "param_name": "Zapach\n/Odour", "kod": None},
        {"row": 2, "param_name": "Wygląd\n/Appearance", "kod": None},
        {"row": 3, "param_name": "Wolne kwasy tłuszczowe [%]\nw przeliczeniu na kwas laurynowy \n(M = 200,3 g/mol)\n/Free fatty acids [%] as lauric acid, (M = 200,3 g/mol)", "kod": "wkt"},
        {"row": 4, "param_name": "MEA [%]  (M = 61,1 g/mol)", "kod": "mea"},
        {"row": 5, "param_name": "Estry [%]\n/Esters [%]", "kod": "estry"},
    ],
    "Świadectwo_Certificate-Monamid KO WZÓR NR ZAM.docx": [
        {"row": 0, "param_name": "Barwa w skali Gardnera\n/Colour (Gardner scale)", "kod": "barwa_hz"},
        {"row": 1, "param_name": "Zapach\n/Odour", "kod": None},
        {"row": 2, "param_name": "Wygląd\n/Appearance", "kod": None},
        {"row": 3, "param_name": "Wolne kwasy tłuszczowe [%]\nw przeliczeniu na kwas laurynowy \n(M = 200,3 g/mol)\n/Free fatty acids [%] as lauric acid, (M = 200,3 g/mol)", "kod": "wkt"},
        {"row": 4, "param_name": "MEA [%]  (M = 61,1 g/mol)", "kod": "mea"},
        {"row": 5, "param_name": "Estry [%]\n/Esters [%]", "kod": "estry"},
    ],
    "Świadectwo_Certificate-Monamid KO WZÓR.docx": [
        {"row": 0, "param_name": "Barwa w skali Gardnera\n/Colour (Gardner scale)", "kod": "barwa_hz"},
        {"row": 1, "param_name": "Zapach\n/Odour", "kod": None},
        {"row": 2, "param_name": "Wygląd\n/Appearance", "kod": None},
        {"row": 3, "param_name": "Wolne kwasy tłuszczowe [%]\nw przeliczeniu na kwas laurynowy \n(M = 200,3 g/mol)\n/Free fatty acids [%] as lauric acid, (M = 200,3 g/mol)", "kod": "wkt"},
        {"row": 4, "param_name": "MEA [%]  (M = 61,1 g/mol)", "kod": "mea"},
        {"row": 5, "param_name": "Estry [%]\n/Esters [%]", "kod": "estry"},
    ],
    "Świadectwo_Certificate-Monester O WZÓR.docx": [
        {"row": 0, "param_name": "Liczba kwasowa [mg KOH/g]\nAcid value [mg KOH/g]", "kod": "lk"},
        {"row": 1, "param_name": "Liczba zmydlania [mg KOH/g]\n/Saponification value [mg KOH/g]", "kod": "lz"},
        {"row": 2, "param_name": "Wsp. załamania światła nD20\n/Refraction index nD20", "kod": "nd20"},
        {"row": 3, "param_name": "Liczba jodowa [g J2/100g]\n/Iodine value [g J2/100g]", "kod": "li"},
    ],
    "Świadectwo_Certificate-Monester S WZÓR.docx": [
        {"row": 0, "param_name": "Liczba kwasowa [mg KOH/g]\nAcid value [mg KOH/g]", "kod": "lk"},
        {"row": 1, "param_name": "Temperatura kroplenia [°C]\n/Dropping point [°C]", "kod": None},
        {"row": 2, "param_name": "Liczba zmydlania [mg KOH/g]\n/Saponification value [mg KOH/g]", "kod": "lz"},
        {"row": 3, "param_name": "Liczba jodowa [g I2/100g]\n/Iodine value [g I2/100g]", "kod": "li"},
    ],
    "Świadectwo_Certificate_Chegina CC - WZÓR.docx": [
        {"row": 0, "param_name": "Wygląd/Appearance", "kod": None},
        {"row": 1, "param_name": "Barwa w skali Hazena\n/Colour (Hazen scale)", "kod": "barwa_hz"},
        {"row": 2, "param_name": "Zapach/Odour", "kod": None},
        {"row": 3, "param_name": "pH (5%, aq, 25°C)", "kod": "ph_10proc"},
        {"row": 4, "param_name": "H2O [%]", "kod": None},
        {"row": 5, "param_name": "NaCl [%]", "kod": "nacl"},
        {"row": 6, "param_name": "Substancja aktywna [%]\n/Active matter [%]", "kod": "sa"},
        {"row": 7, "param_name": "Alkaliczność [meq/g]\n/Total alkalinity [meq/g]", "kod": "alkalicznosc"},
    ],
    "Świadectwo_Certificate_Chegina CCR WZÓR.docx": [
        {"row": 0, "param_name": "Wygląd\n/Appearance", "kod": None},
        {"row": 1, "param_name": "Barwa w skali Hazena\n/Color (Hazen scale)", "kod": "barwa_hz"},
        {"row": 2, "param_name": "Zapach/Odour", "kod": None},
        {"row": 3, "param_name": "pH (5%, aq, 25°C)", "kod": "ph_10proc"},
        {"row": 4, "param_name": "NaCl [%]", "kod": "nacl"},
        {"row": 5, "param_name": "Substancja aktywna [%]\n/Active matter [%]", "kod": "sa"},
    ],
    "test.docx": [
        {"row": 0, "param_name": "Sucha masa [%]\n/Dry matter [%]", "kod": "sm"},
        {"row": 1, "param_name": "NaCl [%]", "kod": "nacl"},
        {"row": 2, "param_name": "Wsp. załamania światła (nD20)\n/Refraction (nD20)", "kod": "nd20"},
        {"row": 3, "param_name": "Barwa w skali jodowej\n/Colour (Iodine scale)", "kod": "barwa_hz"},
        {"row": 4, "param_name": "pH (10%, aq)", "kod": "ph_10proc"},
        {"row": 5, "param_name": "Substancja aktywna [%]\n/Active matter [%]", "kod": "sa"},
    ],
}
